[build]
  publish = "."
  
[[redirects]]
  from = "/"
  to = "/cdl-portal/index.html"
  status = 200

[[redirects]]
  from = "/cdl-portal"
  to = "/cdl-portal/index.html"
  status = 200

[[redirects]]
  from = "/cdl-portal/"
  to = "/cdl-portal/index.html"
  status = 200

[[redirects]]
  from = "/radar/*"
  to = "https://cdlradarmultiuser.vercel.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/cdl-portal/:splat"
  status = 200
